# Generated by Django 5.1.3 on 2024-12-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
    ]
